### ISSUE TITLE
question

### ISSUE THREAD

**Issue by seghier** [bilylee/videofig#2]
how you include videofig inside the code of player ?

**Comment by bilylee** [comment]
Could you supplement your question with more detail? what exactly does the "code of player" mean?

**Comment by seghier** [comment]
if i have image sequence and my code already have videoPlayer how i can use your code to view the images sequence ?
i already create app to convert images sequence to video than view it but i prefer view images only without conversion

**Comment by gongbudaizhe** [comment]
videofig essentially uses two axes handles, `image_axes_handle` in line 161 for displaying images and `scroll_axes_handle` in line 165 for slider. (Note, these code in new branch: custom_fig)

You can embed videofig into your VideoPlayer by using custom axes for these two handles. 

I have added a new branch: `custom_fig` which supports using custom figure handle.  It doesn't directly use custom `axes_handle` and `scroll_axes_handle` but should be a good start for your case.

**Comment by bilylee** [comment]
videofig essentially uses two axes handles, `image_axes_handle in line 161` for displaying images and `scroll_axes_handle in line 165` for slider. (Note, these code in new branch: `custom_fig`)

You can embed videofig into your VideoPlayer by using custom axes for these two handles.

I have added a new branch: `custom_fig` which supports using custom figure handle. It doesn't directly use custom `image_axes_handle` and `scroll_axes_handle` but should be a good start for your case.
