### ISSUE TITLE
Typo on example 2

### ISSUE THREAD

**Issue by JoeHEZHAO** [bilylee/videofig#3]
Hi bilylee

Like your work !

There is a typo on example 2:   
**img_files = glob.glob(os.path.join(video_dir, '*.jpg'))**, I believe video_dir should be img_dir ?

**Comment by bilylee** [comment]
Hi,

Thanks for your interest! 

I use `video_dir`/`img_dir` interchangeably to indicate the directory which contains a sequence of images. The rationale is that **a sequence of images == a video**.  It is true that `video_dir` can also mean a directory containing videos. However, the confusion in this repository should be negligible?

**Comment by JoeHEZHAO** [comment]
Yeah you are right. That's not a big deal.
