### ISSUE TITLE
Visualizing video in Jupyter notebook

### ISSUE THREAD

**Issue by kmundnic** [bilylee/videofig#5]
Is it possible to view a video in a Jupyter notebook? When pressing enter, the cell goes into code-editing mode instead of starting/stopping the video playback. I've tried using both `%matplotlib auto` and `%matplotlib inline` to change the backend in which the images are displayed in the notebook.

Thanks for your help.

**Comment by bilylee** [comment]
Yes, you can. Just use `%matplotlib notebook`

**Comment by kmundnic** [comment]
Thanks! :-)
